export const EmployeeData = [
  {
    firstName: "Cynthia",
    lastName: "Stanwick",
    position: "HR Assistant",
    phone: "(818) 555-6655",
    email: "cindys@dx-email.com",
  },
  {
    firstName: "Greta",
    lastName: "Sims",
    position: "HR Manager",
    phone: "(818) 555-6546",
    email: "gretas@dx-email.com",
  },
  {
    firstName: "Kent",
    lastName: "Samuelson",
    position: "Ombudsman",
    phone: "(562) 555-9282",
    email: "kents@dx-em.com",
  },
  {
    firstName: "Taylor",
    lastName: "Riley",
    position: "Network Admin New",
    phone: "(310) 555-7276",
    email: "taylorr@dx-email.com",
  },
  {
    firstName: "Robert",
    lastName: "Reagan",
    position: "CEO",
    phone: "(818) 555-2387",
    email: "robertr@dx-email.id",
  },
  {
    firstName: "Olivia",
    lastName: "Peyton",
    position: "Sales Assistant",
    phone: "(310) 555-2728",
    email: "oliviap@dx-email.com",
  },
  {
    firstName: "Brett",
    lastName: "Modified",
    position: "IT Manager",
    phone: "(626) 555-0358",
    email: "brettw@dx-email.com",
  },
  {
    firstName: "Sarah",
    lastName: "Johnson",
    position: "Controller",
    phone: "(562) 555-2082",
    email: "sandraj@dx-email.com",
  },
  {
    firstName: "Johnson",
    lastName: "Heart",
    position: "CTO",
    phone: "(213) 555-9392",
    email: "jheart@dx-email.id",
  },
  {
    firstName: "Jackson",
    lastName: "Hansen",
    position: "CEO",
    phone: "(818) 555-2387",
    email: "robertr@dx-email.my",
  },
  {
    firstName: "Kevin",
    lastName: "Carter",
    position: "Shipping Manager",
    phone: "(213) 555-2840",
    email: "kevinc@dx-email.com",
  },
];
